services:
  - type: web
    name: aurex-pubg-clicker-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 8987574004:AAEcFYWsaj1Yt2-VRnts3IW0kK_ClMMZG4E
      - key: OWNER_ID
        value: "8825408278"
      - key: WEBAPP_URL
        value: https://aurex-pubg-clicker-bot.onrender.com
      - key: PORT
        value: 8080

